#!/usr/bin/python

import gio

sub_id = 0

drives = gio.VolumeMonitor().get_connected_drives()

print '<openbox_pipe_menu>'

for drive in drives:

    # get volumes on a drive
    volumes = drive.get_volumes()
    if volumes:
    	# main menu entry
	drive_name = drive.get_name()
	print '<menu id="drives-sub-menu' + str(sub_id) + '\" label=\"' + drive_name + '\">'

	for volume in volumes:
	    volume_str = volume.get_name()
	    volume_ident = volume.get_identifier("unix-device")
	    mount = volume.get_mount()

	    icon = volume.get_icon()
	    if isinstance(icon, gio.ThemedIcon):
		icon_name = icon.get_names()[0]
	    else:
		icon_name = ""

	    # volume icon & label
	    if mount:
		print '<item label=\"[ ' + volume_str + ' ]\" icon=\"' + icon_name + '\">'
	    else:
		print '<item label=\"' + volume_str + '\" icon=\"' + icon_name + '\">'

	    print '<action name="Execute">'

	    if mount:
	    	print '<command>udisksctl unmount -b ' + volume_ident + '</command>'
	    else:
	    	print '<command>udisksctl mount -b ' + volume_ident + '</command>'

	    print '</action>'
	    print '</item>'

	sub_id = sub_id + 1
	print '</menu>'

print '</openbox_pipe_menu>'

